"""
Tests for the Improver agent file structure and pattern detection logic.

Validates the acceptance criteria from the issue:
- Agent file has required sections (monthly trigger, hard boundaries, pattern detection)
- Pattern detection: 3+ lessons in same category → create/update skills/[category]/SKILL.md
- New agent proposal: 5+ lessons in domain with no owner → propose new .agent.md
- PROPOSED_CHANGES.md output format matches template
- Test with 4 hallucination lessons → verify PROPOSED_CHANGES.md has a SKILL.md proposal
"""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

AGENTS_DIR = Path(__file__).resolve().parents[2] / ".github" / "agents"
IMPROVER_FILE = AGENTS_DIR / "improver.agent.md"

SKILL_THRESHOLD = 3
NEW_AGENT_THRESHOLD = 5


def _read_improver() -> str:
    return IMPROVER_FILE.read_text(encoding="utf-8")


def _parse_category(observation: str) -> str | None:
    """Extract category value from a lesson observation string.

    Matches observations starting with 'category:' (no space before the colon).
    The value after the colon is stripped of leading/trailing whitespace, so both
    'category: value' and 'category:value' are handled correctly.
    Returns None if the observation does not start with 'category:'.
    """
    if observation.startswith("category:"):
        return observation.split(":", 1)[1].strip()
    return None


def detect_patterns(lessons: list[dict]) -> list[tuple[str, int]]:
    """Mirror the Pattern Detection Algorithm described in improver.agent.md.

    Query all lesson entities. Group by category observation value.
    If any group has >= 3 entries, it qualifies for a SKILL.md proposal.

    Returns a list of (category, count) tuples for groups meeting the threshold.
    """
    counts: Counter[str] = Counter()
    for lesson in lessons:
        for obs in lesson.get("observations", []):
            category = _parse_category(obs)
            if category:
                counts[category] += 1
    return [(cat, count) for cat, count in counts.items() if count >= SKILL_THRESHOLD]


def detect_new_agent_candidates(lessons: list[dict]) -> list[tuple[str, int]]:
    """Return categories with >= 5 lessons (new agent threshold)."""
    counts: Counter[str] = Counter()
    for lesson in lessons:
        for obs in lesson.get("observations", []):
            category = _parse_category(obs)
            if category:
                counts[category] += 1
    return [(cat, count) for cat, count in counts.items() if count >= NEW_AGENT_THRESHOLD]


def generate_proposed_changes(
    skill_patterns: list[tuple[str, int]],
    new_agent_candidates: list[tuple[str, int]],
    date: str,
) -> str:
    """Produce per-proposal PROPOSED_CHANGES.md entries for a monthly cycle.

    Each qualifying pattern produces a separate ### Proposal: ... block following
    the per-proposal format defined in TEMPLATES.md (required fields: Type, Target
    file, Status, Rationale, Proposed change, Risk level, Protected sections affected).

    The blocks are appended under ## Pending Proposals in PROPOSED_CHANGES.md — they
    do NOT include the top-level heading or other top-level sections.
    """
    blocks: list[str] = []

    for cat, count in skill_patterns:
        blocks.append(
            f"### Proposal: {cat}-skill-update ({date})\n"
            "\n"
            "**Type**: skill-change\n"
            f"**Target file**: `.github/skills/{cat}/SKILL.md`\n"
            "**Status**: PENDING\n"
            "\n"
            "**Rationale**:\n"
            f"{count} lessons in category '{cat}' meet the skill update threshold"
            f" (≥{SKILL_THRESHOLD})."
            " Generated by Improver Agent after monthly lesson review.\n"
            "\n"
            "**Proposed change**:\n"
            f"Create or update `.github/skills/{cat}/SKILL.md` with observations"
            f" from the {count} '{cat}' lessons.\n"
            "\n"
            "**Risk level**: low\n"
            "**Protected sections affected**: none\n"
            "\n"
            "_Human review required — record decision in the Review Log._\n"
            "\n"
            "---"
        )

    for domain, count in new_agent_candidates:
        blocks.append(
            f"### Proposal: new-agent-{domain} ({date})\n"
            "\n"
            "**Type**: new-agent\n"
            f"**Target file**: `.github/agents/{domain}.agent.md`\n"
            "**Status**: PENDING\n"
            "\n"
            "**Rationale**:\n"
            f"Domain '{domain}' appeared {count} times with no existing agent owner,"
            " exceeding the new-agent threshold"
            f" (≥{NEW_AGENT_THRESHOLD})."
            " Generated by Improver Agent after monthly lesson review.\n"
            "\n"
            "**Proposed change**:\n"
            f"Draft a new `.github/agents/{domain}.agent.md` for the '{domain}' domain.\n"
            "\n"
            "**Risk level**: medium\n"
            "**Protected sections affected**: none\n"
            "\n"
            "_Human review required — record decision in the Review Log._\n"
            "\n"
            "---"
        )

    if not blocks:
        return (
            f"_(No proposals generated for this cycle ({date})"
            " — no category thresholds were met.)_"
        )

    return "\n\n".join(blocks)


# ---------------------------------------------------------------------------
# Agent file structure tests
# ---------------------------------------------------------------------------


class TestImproverAgentFileStructure:
    @pytest.fixture(scope="class")
    def content(self) -> str:
        return _read_improver()

    def test_has_hard_boundaries_section(self, content: str) -> None:
        assert "## Hard Boundaries" in content

    def test_hard_boundaries_cannot_modify_agent_files(self, content: str) -> None:
        assert "CANNOT modify existing" in content and ".agent.md" in content

    def test_protected_financial_thresholds_present(self, content: str) -> None:
        assert "<!-- PROTECTED: financial-thresholds -->" in content

    def test_protected_legal_compliance_present(self, content: str) -> None:
        assert "<!-- PROTECTED: legal-compliance -->" in content

    def test_protected_auth_logic_present(self, content: str) -> None:
        assert "<!-- PROTECTED: auth-logic -->" in content

    def test_has_monthly_trigger_section(self, content: str) -> None:
        assert "## Monthly Trigger" in content

    def test_monthly_trigger_runs_on_first_of_month(self, content: str) -> None:
        # Ensure the 1st-of-month trigger is documented
        match = re.search(r"## Monthly Trigger.*?##", content, re.DOTALL)
        assert match, "Could not find ## Monthly Trigger section body"
        section = match.group(0)
        assert "1st of each month" in section

    def test_monthly_trigger_tracks_last_run_metric(self, content: str) -> None:
        match = re.search(r"## Monthly Trigger.*?##", content, re.DOTALL)
        assert match
        section = match.group(0)
        assert "metric:prompt:improver-monthly-cycle:last-run" in section

    def test_has_pattern_detection_algorithm_section(self, content: str) -> None:
        assert "## Pattern Detection Algorithm" in content

    def test_pattern_detection_mentions_skill_threshold(self, content: str) -> None:
        # The algorithm must specify "3" or "≥ 3" as the skill threshold
        match = re.search(r"## Pattern Detection Algorithm.*?##", content, re.DOTALL)
        assert match
        section = match.group(0)
        assert re.search(r"[≥>=]\s*3|3\s*or more", section), (
            "Pattern Detection Algorithm must specify a threshold of 3"
        )

    def test_pattern_detection_mentions_skills_path(self, content: str) -> None:
        match = re.search(r"## Pattern Detection Algorithm.*?##", content, re.DOTALL)
        assert match
        section = match.group(0)
        assert "skills/" in section

    def test_pattern_detection_mentions_new_agent_threshold(self, content: str) -> None:
        # New agent threshold (5+) must appear in the file
        assert re.search(r"5\s*or more|[≥>=]\s*5", content), (
            "Improver must specify 5+ lessons → new agent proposal threshold"
        )

    def test_has_self_improvement_cycle_section(self, content: str) -> None:
        assert "## Self-Improvement Cycle" in content

    def test_has_proposed_changes_format_section(self, content: str) -> None:
        assert "## PROPOSED_CHANGES.md Format" in content

    def test_proposed_changes_format_has_skill_updates(self, content: str) -> None:
        match = re.search(r"## PROPOSED_CHANGES\.md Format.*", content, re.DOTALL)
        assert match
        section = match.group(0)
        # New per-proposal format uses Type field with 'skill-change' value
        assert "skill-change" in section

    def test_proposed_changes_format_has_human_action_required(self, content: str) -> None:
        match = re.search(r"## PROPOSED_CHANGES\.md Format.*", content, re.DOTALL)
        assert match
        section = match.group(0)
        assert "Human review required" in section

    def test_has_trigger_table_section(self, content: str) -> None:
        assert "## Trigger Table" in content

    def test_has_consultation_heuristic_section(self, content: str) -> None:
        assert "## Consultation Heuristic" in content

    def test_consultation_heuristic_matches_canonical_text(self, content: str) -> None:
        canonical = (
            "If your output involves: money amounts, legal claims, auth systems, or cross-product"
            " changes → pause and request peer review before acting, even if no explicit trigger fires."
        )
        match = re.search(r"## Consultation Heuristic\s*\n([^\n]+)", content)
        assert match, "Could not find text after ## Consultation Heuristic"
        assert match.group(1).strip() == canonical


# ---------------------------------------------------------------------------
# Pattern detection logic tests
# ---------------------------------------------------------------------------


class TestPatternDetection:
    def _make_lesson(self, name: str, category: str, summary: str = "summary") -> dict:
        return {
            "type": "entity",
            "name": name,
            "entityType": "lesson",
            "observations": [
                f"category: {category}",
                f"summary: {summary}",
            ],
        }

    def test_no_lessons_returns_empty(self) -> None:
        assert detect_patterns([]) == []

    def test_two_lessons_same_category_below_threshold(self) -> None:
        lessons = [
            self._make_lesson("lesson:2026-03-01:a", "hallucination"),
            self._make_lesson("lesson:2026-03-02:b", "hallucination"),
        ]
        assert detect_patterns(lessons) == []

    def test_three_lessons_same_category_meets_threshold(self) -> None:
        lessons = [
            self._make_lesson("lesson:2026-03-01:a", "hallucination"),
            self._make_lesson("lesson:2026-03-02:b", "hallucination"),
            self._make_lesson("lesson:2026-03-03:c", "hallucination"),
        ]
        patterns = detect_patterns(lessons)
        assert len(patterns) == 1
        cat, count = patterns[0]
        assert cat == "hallucination"
        assert count == 3

    def test_four_hallucination_lessons_produce_skill_proposal(self) -> None:
        """Core acceptance criterion: 4 hallucination lessons → SKILL.md proposal."""
        lessons = [
            self._make_lesson(
                "lesson:2026-03-01:hallucination-1",
                "hallucination",
                "Agent made up a stat",
            ),
            self._make_lesson(
                "lesson:2026-03-02:hallucination-2",
                "hallucination",
                "Agent fabricated a source",
            ),
            self._make_lesson(
                "lesson:2026-03-03:hallucination-3",
                "hallucination",
                "Agent cited wrong law",
            ),
            self._make_lesson(
                "lesson:2026-03-04:hallucination-4",
                "hallucination",
                "Agent invented a deadline",
            ),
        ]
        patterns = detect_patterns(lessons)
        skill_proposals = [f"skills/{cat}/SKILL.md" for cat, _ in patterns]

        assert any("hallucination" in p for p in skill_proposals), (
            "4 hallucination lessons must trigger a skills/hallucination/SKILL.md proposal"
        )

    def test_mixed_categories_only_threshold_group_qualifies(self) -> None:
        lessons = [
            self._make_lesson("lesson:2026-03-01:a", "hallucination"),
            self._make_lesson("lesson:2026-03-02:b", "hallucination"),
            self._make_lesson("lesson:2026-03-03:c", "hallucination"),
            self._make_lesson("lesson:2026-03-04:d", "bug"),
            self._make_lesson("lesson:2026-03-05:e", "bug"),
        ]
        patterns = detect_patterns(lessons)
        categories = [cat for cat, _ in patterns]
        assert "hallucination" in categories
        assert "bug" not in categories

    def test_five_lessons_triggers_new_agent_candidate(self) -> None:
        lessons = [
            self._make_lesson(f"lesson:2026-03-0{i}:a", "wrong-domain")
            for i in range(1, 6)
        ]
        candidates = detect_new_agent_candidates(lessons)
        assert any(cat == "wrong-domain" for cat, _ in candidates)

    def test_four_lessons_does_not_trigger_new_agent_candidate(self) -> None:
        lessons = [
            self._make_lesson(f"lesson:2026-03-0{i}:a", "wrong-domain")
            for i in range(1, 5)
        ]
        candidates = detect_new_agent_candidates(lessons)
        assert not any(cat == "wrong-domain" for cat, _ in candidates)


# ---------------------------------------------------------------------------
# PROPOSED_CHANGES.md format tests
# ---------------------------------------------------------------------------


class TestProposedChangesFormat:
    def _four_hallucination_lessons(self) -> list[dict]:
        return [
            {
                "type": "entity",
                "name": f"lesson:2026-03-0{i}:hallucination-{i}",
                "entityType": "lesson",
                "observations": [
                    "category: hallucination",
                    f"summary: Hallucination incident {i}",
                ],
            }
            for i in range(1, 5)
        ]

    def test_proposed_changes_has_header(self) -> None:
        patterns = detect_patterns(self._four_hallucination_lessons())
        output = generate_proposed_changes(patterns, [], date="2026-03-17")
        # New format: per-proposal header with date
        assert "### Proposal:" in output
        assert "2026-03-17" in output

    def test_proposed_changes_has_generated_by_line(self) -> None:
        patterns = detect_patterns(self._four_hallucination_lessons())
        output = generate_proposed_changes(patterns, [], date="2026-03-17")
        assert "Generated by Improver Agent" in output

    def test_proposed_changes_has_skill_updates_section(self) -> None:
        patterns = detect_patterns(self._four_hallucination_lessons())
        output = generate_proposed_changes(patterns, [], date="2026-03-17")
        # New format uses per-proposal Type field instead of a Skill Updates section
        assert "**Type**: skill-change" in output

    def test_proposed_changes_includes_hallucination_skill_path(self) -> None:
        """Core acceptance criterion: output references skills/hallucination/SKILL.md."""
        patterns = detect_patterns(self._four_hallucination_lessons())
        output = generate_proposed_changes(patterns, [], date="2026-03-17")
        assert "skills/hallucination/SKILL.md" in output

    def test_proposed_changes_has_human_review_note(self) -> None:
        patterns = detect_patterns(self._four_hallucination_lessons())
        output = generate_proposed_changes(patterns, [], date="2026-03-17")
        assert "Human review required" in output

    def test_proposed_changes_no_patterns_shows_none(self) -> None:
        output = generate_proposed_changes([], [], date="2026-03-17")
        # With no patterns the output should indicate no proposals were generated
        assert "No proposals generated" in output
